[page]
offset = 20

[nicloudb]
dbname = "nicloud"
host = "127.0.0.1"
port = 3306
user = "nicloud"
passwd = "123456"

[serveroomdb]
dbname = "bigdata_machine"
host = "127.0.0.1"
port = 3306
user = "machine"
passwd = "machine"

