[page]
offset = 20

[nicloudb]
dbname = "nicloud"
host = "192.168.1.210"
port = 3306
user = "root"
passwd = "West.cn2020"

[serveroomdb]
dbname = "serveroom"
host = "192.168.1.210"
port = 3306
user = "root"
passwd = "West.cn2020"

